# Patient Conversation Prediction

In [222]:
#Importing Libraries
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import csv
import numpy
from nltk.tokenize import word_tokenize


#getting dummies
uploaded = pd.read_csv("train.csv",encoding = 'unicode_escape')
uploaded['Source'] = uploaded['Source'].str.lower()

dummies = pd.get_dummies(uploaded['Source'])
dummies

      blog  facebook  forums  youtube
0        0         0       1        0
1        0         0       1        0
2        1         0       0        0
3        0         0       1        0
4        0         0       1        0
5        0         0       1        0
6        0         0       1        0
7        1         0       0        0
8        0         0       1        0
9        0         0       1        0
10       0         0       1        0
11       0         0       1        0
12       1         0       0        0
13       1         0       0        0
14       0         0       1        0
15       1         0       0        0
16       0         0       1        0
17       1         0       0        0
18       0         0       1        0
19       1         0       0        0
20       1         0       0        0
21       0         0       1        0
22       0         0       1        0
23       0         0       1        0
24       1         0       0        0
25       1         0       0        0
26       1         0       0        0
27       1         0       0        0
28       0         0       1        0
29       1         0       0        0
...    ...       ...     ...      ...
1127     1         0       0        0
1128     1         0       0        0
1129     0         0       1        0
1130     0         0       1        0
1131     1         0       0        0
1132     1         0       0        0
1133     0         0       1        0
1134     1         0       0        0
1135     1         0       0        0
1136     1         0       0        0
1137     0         0       1        0
1138     0         0       1        0
1139     1         0       0        0
1140     0         0       1        0
1141     1         0       0        0
1142     1         0       0        0
1143     0         1       0        0
1144     0         1       0        0
1145     1         0       0        0
1146     0         1       0        0
1147     0         0       1        0
1148     0         0       1        0
1149     1         0       0        0
1150     1         0       0        0
1151     0         0       1        0
1152     1         0       0        0
1153     0         0       0        1
1154     0         0       1        0
1155     0         0       1        0
1156     0         0       1        0

[1157 rows x 4 columns]

In [223]:
#getting file
data_1 = open('train.csv', errors='ignore')
raw1 =data_1.read()

#getting file
data_2 = open('test.csv', errors='ignore')
raw2 = data_2.read()
raw = raw1 + raw2

#Tokenizing word
raw_tok = word_tokenize(raw)

#removing extra symbol and letters
punctuations = '''!()[]{};:.,"\<>/?@#$%^&*_~'0123456789` '''
for elem in punctuations:
    raw_tok = [item.replace(elem, "") for item in raw_tok]

#getting lower form of all letters    
raw_lower  = [word.lower() for word in raw_tok]
#filter out whitespaces
raw_lower = list(filter(None, raw_lower))


#removing stopwords
stop_words = set(stopwords.words('english'))
filtered_word = []
for word in raw_lower:
    if word not in stop_words:
        filtered_word.append(word)
        

#pst = PorterStemmer()
#stem_word = [pst.stem(word) for word in filtered_word]


Vocab = nltk.FreqDist(filtered_word)
len(Vocab)

33721

In [224]:
del Vocab['nt']

In [225]:
def open_with_csv(filename, d='\t'):
    data = []
    with open(filename, errors = 'ignore') as tsvin:
        tie_reader = csv.reader(tsvin, delimiter=d)
        for line in tie_reader:
            data.append(line)
        return data

data_from_csv = open_with_csv('train.csv')

data_token=[]
for sentence in data_from_csv:
    data_token.append([word_tokenize(item) for item in sentence])

In [226]:
punctuations = '''!()[]{};:.,"\<>/?@#$%^&*_~'0123456789`'''
tooo=[]
for sentence in data_token:
    ss=[]
    for word in sentence:
        
        for elem in punctuations:
            word = [item.replace(elem,"") for item in word]
        tooo.append(word)

In [227]:
lowerlist = lambda x: [ y.lower() for y in x]
loww= list(map(lowerlist, tooo))

In [228]:

ver = []
for sentence in loww:
    bag_word = numpy.zeros(len(Vocab))
    for w in sentence:
        for i, word in enumerate(Vocab):
            if word == w:
                bag_word[i] += 1
    ver.append(bag_word)

In [229]:
df = pd.DataFrame(ver)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,33710,33711,33712,33713,33714,33715,33716,33717,33718,33719
0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [236]:
#adding dummies Values
df_1 = pd.DataFrame()
df_1['33720'] = dummies['blog']
df_1['33721'] = dummies['facebook']
df_1['33722'] = dummies['forums']
df_1['33723'] = dummies['youtube']
df_1

      33720  33721  33722  33723
0         0      0      1      0
1         0      0      1      0
2         1      0      0      0
3         0      0      1      0
4         0      0      1      0
5         0      0      1      0
6         0      0      1      0
7         1      0      0      0
8         0      0      1      0
9         0      0      1      0
10        0      0      1      0
11        0      0      1      0
12        1      0      0      0
13        1      0      0      0
14        0      0      1      0
15        1      0      0      0
16        0      0      1      0
17        1      0      0      0
18        0      0      1      0
19        1      0      0      0
20        1      0      0      0
21        0      0      1      0
22        0      0      1      0
23        0      0      1      0
24        1      0      0      0
25        1      0      0      0
26        1      0      0      0
27        1      0      0      0
28        0      0      1      0
29        1      0      0      0
...     ...    ...    ...    ...
1127      1      0      0      0
1128      1      0      0      0
1129      0      0      1      0
1130      0      0      1      0
1131      1      0      0      0
1132      1      0      0      0
1133      0      0      1      0
1134      1      0      0      0
1135      1      0      0      0
1136      1      0      0      0
1137      0      0      1      0
1138      0      0      1      0
1139      1      0      0      0
1140      0      0      1      0
1141      1      0      0      0
1142      1      0      0      0
1143      0      1      0      0
1144      0      1      0      0
1145      1      0      0      0
1146      0      1      0      0
1147      0      0      1      0
1148      0      0      1      0
1149      1      0      0      0
1150      1      0      0      0
1151      0      0      1      0
1152      1      0      0      0
1153      0      0      0      1
1154      0      0      1      0
1155      0      0      1      0
1156      0      0      1      0

[1157 rows x 4 columns]

In [231]:
target = pd.read_csv("train.csv",encoding = 'unicode_escape')['Patient_Tag'].tolist()

In [232]:
df = df[:-1]

In [233]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(df,target,test_size=0.10, random_state = 5)

In [234]:
from sklearn.naive_bayes import MultinomialNB

clf = MultinomialNB(alpha=1)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(metrics.accuracy_score(y_test, y_pred))

0.75

In [235]:
score = confusion_matrix(y_test, y_pred)
score

array([[87,  8],
       [21,  0]], dtype=int64)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(y_test,y_pred))

# SVC

In [ ]:
from sklearn.svm import SVC # "Support Vector Classifier" 
clf = SVC(kernel='linear') 
  
# fitting x samples and y classes 
clf.fit(X_train, y_train)

In [ ]:
y_pred = clf.predict(X_test)
print(metrics.accuracy_score(y_test, y_pred))

In [ ]:
score = confusion_matrix(y_test, y_pred)
score

In [ ]:
p = score[0,0]/(score[0,0]+score[0,1])
print('p: ',p,' r: ',r)
r = score[0,0]/(score[0,0]+score[1,0])
f1=2*(p*r/(p+r))
f1